#ifndef TPXL_INTERNAL_THREAD_H
#define TPXL_INTERNAL_THREAD_H

typedef enum {
    THREAD_STATUS_UNKNOWN = 0,
    THREAD_RUNNING,
    THREAD_WAITING,
    THREAD_FINISHED,
    THREAD_ERROR
} TpxlThreadStatus;

#endif
