#ifndef TPXL_INTERNAL_THREAD_H
#define TPXL_INTERNAL_THREAD_H

typedef enum {
    TPXL_THREAD_STATUS_UNKNOWN = 0,
    TPXL_THREAD_RUNNING,
    TPXL_THREAD_WAITING,
    TPXL_THREAD_FINISHED,
    TPXL_THREAD_ERROR
} TpxlThreadStatus;

#endif
